modLoader = "javafml"
loaderVersion = "[39,)"

authors = "${author}"
license = "${license}"
issueTrackerURL = "${issuesURL}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
description = "${description}"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"
